services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: rails_production

    ports:
      - "5432:5432"

    volumes:
      - pg_data:/var/lib/postgresql/data

  rails-nginx:
    build:
      context: .
      dockerfile: Dockerfile

    image: rails-nginx-test:latest
    container_name: rails-nginx

    depends_on:
      - postgres-db

    restart: unless-stopped

    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: 82bd6aa4873741005e93300e00406fbb
      SECRET_KEY_BASE: dummysecret123
      DB_HOST: postgres-db
      DB_NAME: rails_production
      DB_USER_NAME: rails
      DB_PASSWORD: secret123

    ports:
      - "80:80"

volumes:
  pg_data: