name: Deploy

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::247332612707:role/github-actions-rails-store
          aws-region: ap-south-2

      - name: Create Zip
        run: |
          zip -r source.zip . \
          -x ".git/*" \
          -x ".github/*"

      - name: Upload Source
        run: |
          aws s3 cp source.zip s3://rails-store-source-2563d27c/source.zip

      - name: Trigger Pipeline
        run: |
          aws codepipeline start-pipeline-execution \
            --name rails-store-pipeline